#!/bin/bash

# Setup script for Docker Debian hosts

######## Use as Root ############

# Install Docker (Source: docs.docker.com)

# First step update apt-get
apt update && apt upgrade && apt full-upgrade && apt autoremove && apt clean

apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y;

# Add Docker key to apt
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# Check fingerprint
apt-key fingerprint 0EBFCD88;

# For x86_64/AMD64 Hosts
# add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

# Test Architecture
if [[ $(uname -m) != *arm* ]]
then
        # For AMD64 Hosts
        echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list;
else
        # For ARM Hosts
        echo "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list;
fi
# Update apt and install docker-ce
apt-get update &&  apt-get install docker-ce docker-ce-cli containerd.io;

# Install Docker-Compose

# Test Architecture
if [[ $(uname -m) != *arm* ]]
then
        # DOwnload executable
        sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        # Set executable Flag for the executable
        chmod +x /usr/local/bin/docker-compose
else
        # Compile and install Docker-Compose for ARM
        # Script copier from https://www.berthon.eu/2017/getting-docker-compose-on-raspberry-pi-arm-the-easy-way/

        git clone https://github.com/docker/compose.git
        
        cd compose
        git checkout release
        
        # cp -i Dockerfile Dockerfile.armhf
       # sed -i -e 's/^FROM debian\:/FROM armhf\/debian:/' Dockerfile.armhf
       # sed -i -e 's/x86_64/armel/g' Dockerfile.armhf

        #docker build -t docker-compose:armhf -f Dockerfile.armhf .
        docker build -t docker-compose:armhf -f Dockerfile .
        docker run --rm --entrypoint="script/build/linux-entrypoint" -v $(pwd)/dist:/code/dist -v $(pwd)/.git:/code/.git "docker-compose:armhf"

        cp dist/docker-compose-Linux-armv7l /usr/local/bin/docker-compose
        chown root:root /usr/local/bin/docker-compose
        chmod 0755 /usr/local/bin/docker-compose
        docker-compose version

        curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

        cd ..
        rm -r compose
fi
